/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** OK */
        200: unknown
      }
    }
  }
  '/plants': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.plants.id']
          user_id?: parameters['rowFilter.plants.user_id']
          name?: parameters['rowFilter.plants.name']
          last_watering?: parameters['rowFilter.plants.last_watering']
          watered_interval?: parameters['rowFilter.plants.watered_interval']
          created_at?: parameters['rowFilter.plants.created_at']
          deleted_at?: parameters['rowFilter.plants.deleted_at']
          /** Filtering Columns */
          select?: parameters['select']
          /** Ordering */
          order?: parameters['order']
          /** Limiting and Pagination */
          offset?: parameters['offset']
          /** Limiting and Pagination */
          limit?: parameters['limit']
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range']
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit']
          /** Preference */
          Prefer?: parameters['preferCount']
        }
      }
      responses: {
        /** OK */
        200: {
          schema: Array<definitions['plants']>
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** plants */
          plants?: definitions['plants']
        }
        query: {
          /** Filtering Columns */
          select?: parameters['select']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.plants.id']
          user_id?: parameters['rowFilter.plants.user_id']
          name?: parameters['rowFilter.plants.name']
          last_watering?: parameters['rowFilter.plants.last_watering']
          watered_interval?: parameters['rowFilter.plants.watered_interval']
          created_at?: parameters['rowFilter.plants.created_at']
          deleted_at?: parameters['rowFilter.plants.deleted_at']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.plants.id']
          user_id?: parameters['rowFilter.plants.user_id']
          name?: parameters['rowFilter.plants.name']
          last_watering?: parameters['rowFilter.plants.last_watering']
          watered_interval?: parameters['rowFilter.plants.watered_interval']
          created_at?: parameters['rowFilter.plants.created_at']
          deleted_at?: parameters['rowFilter.plants.deleted_at']
        }
        body: {
          /** plants */
          plants?: definitions['plants']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
  '/users': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.users.id']
          full_name?: parameters['rowFilter.users.full_name']
          /** Filtering Columns */
          select?: parameters['select']
          /** Ordering */
          order?: parameters['order']
          /** Limiting and Pagination */
          offset?: parameters['offset']
          /** Limiting and Pagination */
          limit?: parameters['limit']
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range']
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit']
          /** Preference */
          Prefer?: parameters['preferCount']
        }
      }
      responses: {
        /** OK */
        200: {
          schema: Array<definitions['users']>
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions['users']
        }
        query: {
          /** Filtering Columns */
          select?: parameters['select']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.users.id']
          full_name?: parameters['rowFilter.users.full_name']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.users.id']
          full_name?: parameters['rowFilter.users.full_name']
        }
        body: {
          /** users */
          users?: definitions['users']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
  '/watering': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.watering.id']
          plant_id?: parameters['rowFilter.watering.plant_id']
          watering_date?: parameters['rowFilter.watering.watering_date']
          /** Filtering Columns */
          select?: parameters['select']
          /** Ordering */
          order?: parameters['order']
          /** Limiting and Pagination */
          offset?: parameters['offset']
          /** Limiting and Pagination */
          limit?: parameters['limit']
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range']
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit']
          /** Preference */
          Prefer?: parameters['preferCount']
        }
      }
      responses: {
        /** OK */
        200: {
          schema: Array<definitions['watering']>
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** watering */
          watering?: definitions['watering']
        }
        query: {
          /** Filtering Columns */
          select?: parameters['select']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.watering.id']
          plant_id?: parameters['rowFilter.watering.plant_id']
          watering_date?: parameters['rowFilter.watering.watering_date']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.watering.id']
          plant_id?: parameters['rowFilter.watering.plant_id']
          watering_date?: parameters['rowFilter.watering.watering_date']
        }
        body: {
          /** watering */
          watering?: definitions['watering']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
  '/rpc/handle_new_user': {
    post: {
      parameters: {
        body: {
          args: { [key: string]: any }
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferParams']
        }
      }
      responses: {
        /** OK */
        200: unknown
      }
    }
  }
  '/rpc/handle_new_watering': {
    post: {
      parameters: {
        body: {
          args: { [key: string]: any }
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferParams']
        }
      }
      responses: {
        /** OK */
        200: unknown
      }
    }
  }
}

export interface definitions {
  plants: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number
    /**
     * Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string
    name: string
    last_watering?: string
    watered_interval?: number
    created_at: string
    deleted_at?: string
  }
  users: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    id: string
    full_name?: string
  }
  watering: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number
    /**
     * Note:
     * This is a Foreign Key to `plants.id`.<fk table='plants' column='id'/>
     */
    plant_id: number
    watering_date: string
  }
}

export interface parameters {
  /** Preference */
  preferParams: 'params=single-object'
  /** Preference */
  preferReturn: 'return=representation' | 'return=minimal' | 'return=none'
  /** Preference */
  preferCount: 'count=none'
  /** Filtering Columns */
  select: string
  /** On Conflict */
  on_conflict: string
  /** Ordering */
  order: string
  /** Limiting and Pagination */
  range: string
  /** Limiting and Pagination */
  rangeUnit: string
  /** Limiting and Pagination */
  offset: string
  /** Limiting and Pagination */
  limit: string
  /** plants */
  'body.plants': definitions['plants']
  'rowFilter.plants.id': string
  'rowFilter.plants.user_id': string
  'rowFilter.plants.name': string
  'rowFilter.plants.last_watering': string
  'rowFilter.plants.watered_interval': string
  'rowFilter.plants.created_at': string
  'rowFilter.plants.deleted_at': string
  /** users */
  'body.users': definitions['users']
  'rowFilter.users.id': string
  'rowFilter.users.full_name': string
  /** watering */
  'body.watering': definitions['watering']
  'rowFilter.watering.id': string
  'rowFilter.watering.plant_id': string
  'rowFilter.watering.watering_date': string
}

export interface operations {}
