/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  plants: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number
    /**
     * Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string
    name: string
    watered_interval?: number
    created_at: string
    deleted_at?: string
    last_watering?: string
  }
  users: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    id: string
    name?: string
  }
  /**
   * no plantId key
   */
  watering: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number
    /**
     * Note:
     * This is a Foreign Key to `plants.id`.<fk table='plants' column='id'/>
     */
    plant_id: number
    watering_date: string
  }
}
